### PR TITLE
Drupal: Redis

### PR DESCRIPTION
**Pull request by kanei**

### CODE REVIEW

**Comment by miromichalicka** [comment]
waiting for infra to catchup

**Comment by radkoa** [comment]
Are we still going to use this?

**Comment by kanei** [comment]
> Are we still going to use this?

Might be. Depends on the final insfrastructure.

**Comment by miromichalicka** [comment]
Checking with Honza Vlasak

**Comment by miromichalicka** [comment]
Fixed in #368

**Pull request closed without merging**
