### PR TITLE
fix: gatsby - moved build message to footer

### PR DESCRIPTION
**Pull request by rostaklein**
alert in the header is way too distracting + causes the mobile menu buggy

theres no need to have it that big, lets put it into the footer :) 
image

### CODE REVIEW

**Comment by vitkolos** [comment]
put gatsby/config/gatsby-node.ts back please

**Comment by rostaklein** [comment]
Heh, i removed it kinda by mistake :D But we have to adjust it... every single time theres some type changed, the whole compilation stops and the only way is to rebuild the whole FE 😢

**Comment by vitkolos** [comment]
I think we should remove it… except the `export { createPages } from './create-pages';` part. 😁

**Comment by vitkolos** [comment]
Well, I use DISABLE_TYPE_CHECK env variable, but there's a catch – there's a `===` with a string so you have to define the env variable as a string not a boolean.

**Comment by rostaklein** [comment]
ah, thats why it failed :D okay, ill try to adjust it, we will keep the lint up to CI

**Comment by vitkolos** [comment]
You were editing the footer so I'd like to encourage you to do these two things:
1. remove the footer__brand class
2. change col-12 col-sm-6 to just col-12

There's a card in Trello for it, I hope.

Or we can do it some other day. 🤷‍♂️ It's up to you.

**Review by vitkolos — APPROVED** [review]

**Pull request merged**
